//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.emprunt = new HashSet<emprunt>();
        }
    
        public int idClient { get; set; }
        public string nomClient { get; set; }
        public string prenomClient { get; set; }
        public string emailClient { get; set; }
        public System.DateTime dateAbonnementClient { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public int actif { get; set; }
        public Nullable<int> admin { get; set; }
    
        public virtual ICollection<emprunt> emprunt { get; set; }
    }
}
