//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3
{
    using System;
    using System.Collections.Generic;
    
    public partial class serie
    {
        public serie()
        {
            this.saison = new HashSet<saison>();
        }
    
        public int idSerie { get; set; }
        public string resumeSerie { get; set; }
    
        public virtual ICollection<saison> saison { get; set; }
        public virtual support support { get; set; }
    }
}
